Add `Zeroize` to private key
radixdlt/radixdlt-scrypto pull request #1770
Opened 2024-04-12 12:51 UTC by mstrug-rdx

## Summary
Added derive of `Zeroize` and `ZeroizeOnDrop` to `Ed25519PrivateKey`. This is required by Sargon project (will be used thorught RET).

2024-04-13 07:20 UTC, CyonAlexRDX requested changes
Thx! But I need it on Secp256k1PrivateKey as well :)

2024-04-15 11:13 UTC, mstrug-rdx commented
@CyonAlexRDX I did some implementation which uses `SecretKey::non_secure_erase()` as default value but it fills slice with 1's.

2024-04-15 11:59 UTC, CyonAlexRDX commented
> @CyonAlexRDX I did some implementation which uses `SecretKey::non_secure_erase()` as default value but it fills slice with 1's.

All ones is not a valid Secp256k1PrivateKey. It is larger than the order of the curve. So best replace the key with the key 31 zeroes followed by 1, i.e the key `0d1`

2024-04-16 09:40 UTC, CyonAlexRDX approved these changes
LGTM!

Maybe add a unit tests that calls `zeroize()` on a non `1` private key and assert that it becomes `SecretKeyWrapper::default()`?

2024-04-17 08:23 UTC, merged