Feature/timestamp check
radixdlt/radixdlt-scrypto pull request #1950
Opened 2024-10-08 10:29 UTC by iamyulong

## Summary

Add timestamp check

2024-10-08 15:01 UTC, dhedey requested changes
Nice! But there's a couple of tweaks we need I think

2024-10-08 15:04 UTC, iamyulong commented on radix-engine/src/system/system_callback.rs
> +                    RejectionReason::InvalidTimestampRange {
Will do.

2024-10-08 15:05 UTC, iamyulong commented on radix-engine/src/system/system_callback.rs
> +        if let Some(range) = executable.overall_proposer_timestamp_range() {
See `pub fn overall_proposer_timestamp_range(&self) -> Option<&ProposerTimestampRange>`.

Am I missing something?

2024-10-08 15:07 UTC, iamyulong commented on radix-engine-tests/tests/kernel/transaction_executor.rs
> +#[test]
The second case is covered by all the existing "scenarios".

Not sure how much extra value I get from the first case, but will add anyway.

2024-10-08 15:07 UTC, iamyulong commented on radix-engine-tests/tests/kernel/transaction_executor.rs
> +    );
It's covered by all the receipt assertions, see PR diff.

2024-10-08 15:10 UTC, iamyulong commented on radix-transaction-scenarios/generated-examples/cuttlefish/basic_subintents/costings/001--create-accounts.txt
> +- CheckTimestamp                                                           ,                    40000,      0.6%
To be clear, are we suggesting that we skip validation if the range is `(-infinity, infinity)`.

We got a `Some(range)` from the executable, thus the costing above.

2024-10-08 15:20 UTC, dhedey commented on radix-engine-tests/tests/kernel/transaction_executor.rs
> +#[test]
Discussed on the call, I think it'd be good to have a test:
> Ensure that a v2 transaction without any timestamp assertion is not billed for reading the timestamp.

2024-10-08 15:21 UTC, dhedey commented on radix-engine-tests/tests/kernel/transaction_executor.rs
> +    );
True, although the receipt assertions are incorrect for the v2 transactions :)

2024-10-08 15:22 UTC, dhedey commented on radix-engine-tests/tests/kernel/transaction_executor.rs
> +#[test]
> Not sure how much value we can get from the first case, but will add anyway.

Well imo it verifies the three cases the node cares about:
* `RejectionReason::TransactionProposerTimestampNotYetValid`
* (not reject)
* `RejectionReason::TransactionProposerTimestampNoLongerValid`

And e.g. would catch us getting the rejection reasons round the wrong way or something :D

2024-10-10 20:58 UTC, dhedey approved these changes
Nice.

Sorry - looks like there's some merge conflicts with https://github.com/radixdlt/radixdlt-scrypto/pull/1943 - should be easy to resolve though I hope 👍

2024-10-14 07:37 UTC, merged