Fix/powi overflow and tighter integers
radixdlt/radixdlt-scrypto pull request #676
Opened 2022-12-09 20:28 UTC by arthurvinci

This PR solves overflow errors in the `powi` function. The following code would overflow at every line involving  `powi`:
```Rust
    #[test]
    fn test_powi_max_decimal() {
        let _max_bug = Decimal::MAX.powi(1);
        let _max_sqrt = Decimal::MAX.sqrt().unwrap();
        let _max_cbrt = Decimal::MAX.cbrt();
        let _max_dec_2 = _max_sqrt.powi(2);
        let _max_dec_3 = _max_cbrt.powi(3);
    }
    ```
    
    The PR also changes integer used in root function of `Decimal` and `PreciseDecimal` to tighter integers (I384 and I768 as suggested by @r001)

2022-12-09 22:04 UTC, r001 requested changes

2022-12-09 22:04 UTC, r001 commented on radix-engine-interface/src/math/decimal.rs
> +            return Decimal(self.0) * sub_dec.powi(div(sub(exp, 1), 2));
Please change `Decimal(self.0)` to `*self`.

2022-12-09 22:04 UTC, r001 commented on radix-engine-interface/src/math/decimal.rs
> +            return Decimal(self.0);
Please change `Decimal(self.0)` to `*self`! Thanks

2022-12-09 22:05 UTC, r001 commented
Another great PR to make Scrypto even safer. 🎉 Thanks @arthurvinci! 
Highly appreciate your work!

2022-12-17 20:41 UTC, r001 approved these changes

2022-12-17 20:46 UTC, r001 requested changes
Please rebase this on `betanet-v1` branch instead of develop.
Thank you, otherwise its all approved.

2022-12-18 10:45 UTC, arthurvinci commented
@r001 Done. I am not sure it is doing what you expected though.

2022-12-19 20:32 UTC, r001 commented
Not really. I think what you should do is just clone the `betanet-v1` and copy the files you changed on top of it. 
If you can force `-f` push here, that would be great, if not, then create a new PR.

2022-12-20 16:54 UTC, r001 commented
@arthurvinci this is not as simple unfortunately as to just set the branch to `betanet-v1`. Your original branch was probably `develop`, which currently differ from `betanet-v1` as we are adding different changes to both. So what I suggest you to do is : 

1. Please pull `betanet-v1`.
2. Issue your changes made to files, rename branch to `fix/powi_overflow_and_tighter_integers`.
3. Force push to `arthurvinci:fix/powi_overflow_and_tighter_integers`.
4. If 3. does not work, then create a new PR, I will accept it. 
5. Done merged.

2022-12-20 18:11 UTC, arthurvinci commented
@r001 This is what I did in #693 maybe I should have used a better name though.

2022-12-21 10:45 UTC, arthurvinci commented
#693 solves the issues and makes required changes

2022-12-21 10:45 UTC, closed without merging